CREATE TABLE IF NOT EXISTS Drug (
    ID INTEGER PRIMARY KEY,
    NAME_ABBR TEXT NULL,
    "NUMBER" REAL NULL,
    NAME_STD TEXT,
    NOTES TEXT,
    NUM_ADV_REACTIONS REAL,
    ADV_REA_ID_CODE TEXT,
    BEST_OVERALL TEXT,
    PHARMA_MAX_LEN TEXT,
    PHARMA_ID_CODE TEXT,
    REPRESENTATIVE_PRODUCT_NAME TEXT,
    SECTION TEXT,
    FOR_ANALYSIS TEXT,
    PHARMACOLOGY TEXT,
    ADV_REACTIONS TEXT,
    ADV_REA_BEST_DRUG_RAW_ID INTEGER,
    PHARM_BEST_DRUG_RAW_ID INTEGER,
    ANALYSE INTEGER,
    MECHANISM TEXT
);

CREATE TABLE IF NOT EXISTS Reaction (
    ID INTEGER PRIMARY KEY,
    REACTION TEXT,
    SEMANTIC_LOOKUP_STRING TEXT
);

CREATE TABLE IF NOT EXISTS DrugReaction (
    DRUG_ID INTEGER  NOT NULL,
    REACTION_ID INTEGER NOT NULL,
    DRUG_NAME_STD TEXT,
    REACTION TEXT,
    LIKELIHOOD TEXT,
    AGE TEXT,
    DISCLAIMER TEXT,
    DISCONTINUE TEXT,
    DOSAGE TEXT,
    FORM TEXT,
    USAGE TEXT,
    PRIMARY KEY(DRUG_ID, REACTION_ID)
);